language: groovy
jdk:
- oraclejdk7
branches:
  only:
  - developer
script: ./grailsw refresh-dependencies && ./grailsw "test-app unit:" && ./grailsw war webapps/ROOT.war
deploy:
  provider: openshift
  user: hsingh@iworkscorp.com
  password:
    secure: PpsxfZVmxLTQCLe+TcoUJB6PSj9E2YtybbC44wbnVt2UhCniajdZ0khgFBBr7Q88NTjZAY44gr0eW6UsSPL5w7/s40lo7McW+YFM52BuTFlyFuSXuSTGrtn55yPOE1mYmPFT/mK3oVZf+zvNQQidHUR5YPte5zgzK3Z5/HJYi2W4LMLOid5uolIpK4HdTMpHGhgerHqnpeDrJ7qyMckHw6i1+vkaQnNTKguzRSK2BqHzfCaZ5cZvP0lTmW2+SKa56q2MM0kV+P9fkB50m6HEM77vzMwzlrvlhsKC/u8QhgrBuxegYAzpMnbAGN4hI9KZho34o0pDfdb7fS17RUxjbB0D+7DjFWH+dksWx+jRkGEuyKi8DMTnbO6rVfFOmxFYaPJ1SUiOYteDi4DKQf2X02pnaoFj/rOztW7ZXHurCrZcWjGEBatpEuJVsyIupM+Yk2RIhuKpF+kHDRNUW8nuWL8b09/MMs3HJWBReK92HoFd3/dK4V+1S+W+pg7P2U0McpENHU8/yCQvc2SsKVdp9Bsv3z0HTYaixsUGpqwp5p4RfanNT3aaLqu68Ekk+8eEVovEmxUd9U+kIj+e2PC3QCFbE/nFTtezpChTs5Oqie9suRpx5TmBfjyoI8G7K5XUo4wm/P7wW7564CLqGRjPzcGkJF8QpaFQBofMIY+Hfd4=
  app: 18fpocdev
  domain: iworksfda
  on:
    repo: iworkscorp/18fpoc
    branch: developer
after_success:
  - git init
  - git config --global user.email "travis@localhost.localdomain"
  - git config --global user.name "Travis CI"
  - git add --all
  - git commit -am "Travis change"
  - git push origin developer
