language: groovy
jdk:
  - oraclejdk7
branches:
  only:
    - developer
script: ./grailsw refresh-dependencies
  && ./grailsw "test-app unit:"

deploy:
  provider :openshift
  user:'hsingh@iworkscorp.com'
  password:'YdVfA7dBVv'
  app:
    developer:'jbossews'
    master:'18fpoc'
  domain:'iworksfda'
